fix: use absolute URLs for model metadata references
Sound training projects were failing to load because of the
relative URL used.

Error: Unsupported URL scheme in metadata URL:
/static/bower_components/tensorflow-models/.../metadata.json.
Supported schemes are: http://, https://

Signed-off-by: Dale Lane <dale.lane@uk.ibm.com>